# Generated by Django 5.1 on 2024-09-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Reg_no', models.IntegerField(max_length=20)),
                ('Maths', models.IntegerField(max_length=10)),
                ('Physics', models.IntegerField(max_length=10)),
                ('Chemistry', models.IntegerField(max_length=10)),
                ('English', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
