# Generated by Django 5.1 on 2024-09-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_student_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_details', models.CharField(max_length=100)),
                ('Product_price', models.IntegerField()),
                ('Product_rating', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
